apiVersion: apps/v1
kind: deployment
metadata:
  name: deploy01
  matchLabels:
    app: web
spec:
  replicas: 1
  template:
    metadata:
      name: tomcat-pod
      labels:
        app: web
    spec:
      containers:
        image: ${ACR_LOGINSERVER}/${project}:${ImageTag}
        ports:
        - containerPort: 8080
---
apiVersion: v1 
kind: Service
metadata:
  name: svc01
spec:
  selector:
    app: web
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 9090
---